// import React from 'react'

// export const metadata = {
//   title: {
//     default:"learning",
//     template:"%s| learning next js"
//   },
//   description: "Generated by create next app",
// };
'use client';

import React, { useEffect, useState } from 'react';
export const servicesData = [
  {
    icon: "📝",
    title: "অনলাইন রেজিস্ট্রেশন",
    description: "সহজ অনলাইন রেজিস্ট্রেশন প্রক্রিয়া, যেখানে আপনি আপনার তথ্য, ব্যাচ ও ছবি আপলোড করতে পারবেন।"
  },
  {
    icon: "🎁",
    title: "ওয়েলকাম প্যাকেজ",
    description: "আইডি কার্ড, গিফট ব্যাগ, টি-শার্ট ও ব্যাজ সহ একটি স্পেশাল ওয়েলকাম প্যাকেজ।"
  },
  {
    icon: "🍽️",
    title: "খাবার ও ক্যাটারিং",
    description: "দুপুর ও রাতের খাবারের সু-ব্যবস্থা থাকবে ভেজ/নন-ভেজ অপশন সহ।"
  },
  {
    icon: "🎤",
    title: "সাংস্কৃতিক অনুষ্ঠান",
    description: "নাচ, গান, নাটক এবং ব্যাচ ভিত্তিক প্রতিভা প্রদর্শনের আয়োজন।"
  },
  {
    icon: "📸",
    title: "ফটোগ্রাফি ও ভিডিওগ্রাফি",
    description: "ইভেন্ট কভারেজ সহ ছবি ও ভিডিও পরবর্তীতে Google Drive এ শেয়ার করা হবে।"
  },
  {
    icon: "🚌",
    title: "পরিবহন ব্যবস্থা",
    description: "নির্দিষ্ট লোকেশন থেকে বাস সার্ভিস ও পর্যাপ্ত পার্কিং সুবিধা।"
  }
];



 // for client component



export default function Service() {
  const [services, setServices] = useState(servicesData);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getServices = async () => {
      try {
        const res = await fetch('/app/service'); // API route বা public JSON path
        const data = await res.json();
        setServices(data);
      } catch (error) {
        console.error("Error fetching services:", error);
      } finally {
        setLoading(false);
      }
    };

    getServices();
  }, []);

  return (
    <div className="bg-gray-100 py-12 px-6 md:px-20">
      <h2 className="text-3xl font-bold text-center text-gray-800 mb-10">আমাদের সেবাসমূহ</h2>

      {loading ? (
        <p className="text-center text-gray-600">লোড হচ্ছে...</p>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
          {services.map((service, index) => (
            <div
              key={index}
              className="bg-white rounded-2xl shadow-md p-6 hover:shadow-xl transition-all duration-300"
            >
              <div className="text-4xl mb-4 text-center">{service.icon}</div>
              <h3 className="text-xl font-semibold text-center mb-2 text-indigo-600">{service.title}</h3>
              <p className="text-gray-600 text-sm text-center">{service.description}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

